"""Fixture customer profiles for Personal AI Shopping Agent v1.

Demo personas only — no login, cloud sync, or purchase history.
"""

from __future__ import annotations

from typing import Any

from app.domain.entities.personal_agent import CustomerProfile
from app.intelligence.shopping_assistant.fixtures import (
    IPHONE_DEMO_PRODUCT_ID,
    get_catalog,
)

DEFAULT_PROFILE_ID = "profile-budget-student"

LIMITATIONS: tuple[str, ...] = (
    "Profiles are fixtures / demo personas only.",
    "No login, authentication, or cloud sync.",
    "No purchase history or payment history.",
    "No user tracking or behavioral analytics.",
    "Recommendations remain evidence-based; personalization never fabricates fit.",
    "Personal DealScore composes catalog DealScore with profile preferences only.",
)


def _profile(**kwargs: Any) -> CustomerProfile:
    return CustomerProfile(**kwargs)


DEMO_PROFILES: tuple[CustomerProfile, ...] = (
    _profile(
        profile_id="profile-budget-student",
        display_name="Budget Student",
        persona="budget_student",
        budget=35000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Shopee", "Lazada"),
        favorite_brands=("Lenovo", "Acer", "Google"),
        disliked_brands=("Apple",),
        preferred_screen_sizes=("14", "15"),
        preferred_colors=("black", "gray"),
        gaming=False,
        office_work=True,
        student=True,
        creator=False,
        traveler=False,
        battery_priority=0.8,
        performance_priority=0.45,
        camera_priority=0.35,
        storage_priority=0.55,
        price_sensitivity=0.95,
        upgrade_frequency="rare",
        owned_products=(),
        wishlist=("sa-phone-pixel-9",),
        favorite_categories=("laptop", "phone"),
        accessories_owned=(),
        description="Tight budget, needs reliable study laptop or phone under ₱35k.",
    ),
    _profile(
        profile_id="profile-gaming-enthusiast",
        display_name="Gaming Enthusiast",
        persona="gaming_enthusiast",
        budget=60000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Shopee",),
        favorite_brands=("ASUS", "Lenovo", "Acer"),
        disliked_brands=(),
        preferred_screen_sizes=("15", "16"),
        preferred_colors=("black",),
        gaming=True,
        office_work=False,
        student=False,
        creator=False,
        traveler=False,
        battery_priority=0.35,
        performance_priority=0.95,
        camera_priority=0.2,
        storage_priority=0.7,
        price_sensitivity=0.55,
        upgrade_frequency="frequent",
        owned_products=(),
        wishlist=("sa-laptop-loq-15", "sa-laptop-tuf-a15"),
        favorite_categories=("laptop",),
        accessories_owned=(),
        description="Prioritizes GPU performance and DealScore under ₱60k.",
    ),
    _profile(
        profile_id="profile-photographer",
        display_name="Photographer",
        persona="photographer",
        budget=70000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Shopee", "Lazada"),
        favorite_brands=("Apple", "Google", "Samsung"),
        disliked_brands=(),
        preferred_screen_sizes=("6.1", "6.8"),
        preferred_colors=("black", "titanium"),
        gaming=False,
        office_work=False,
        student=False,
        creator=True,
        traveler=True,
        battery_priority=0.75,
        performance_priority=0.65,
        camera_priority=0.98,
        storage_priority=0.8,
        price_sensitivity=0.4,
        upgrade_frequency="yearly",
        owned_products=(),
        wishlist=(IPHONE_DEMO_PRODUCT_ID, "sa-phone-galaxy-s25-ultra", "sa-phone-pixel-9"),
        favorite_categories=("phone", "laptop"),
        accessories_owned=(),
        description="Camera and battery first; phones and light editing laptops.",
    ),
    _profile(
        profile_id="profile-business-traveler",
        display_name="Business Traveler",
        persona="business_traveler",
        budget=65000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Shopee",),
        favorite_brands=("Apple", "Lenovo"),
        disliked_brands=("Acer",),
        preferred_screen_sizes=("13", "14"),
        preferred_colors=("silver", "midnight"),
        gaming=False,
        office_work=True,
        student=False,
        creator=False,
        traveler=True,
        battery_priority=0.95,
        performance_priority=0.6,
        camera_priority=0.4,
        storage_priority=0.5,
        price_sensitivity=0.45,
        upgrade_frequency="biennial",
        owned_products=("sa-earbuds-airpods-pro-2",),
        wishlist=("sa-laptop-macbook-air-m3",),
        favorite_categories=("laptop", "earbuds"),
        accessories_owned=("sa-earbuds-airpods-pro-2",),
        description="Light, quiet ultraportable with long battery for flights.",
    ),
    _profile(
        profile_id="profile-content-creator",
        display_name="Content Creator",
        persona="content_creator",
        budget=70000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Lazada", "Shopee"),
        favorite_brands=("Lenovo", "ASUS", "Samsung", "Apple"),
        disliked_brands=(),
        preferred_screen_sizes=("15", "16"),
        preferred_colors=("black",),
        gaming=True,
        office_work=False,
        student=False,
        creator=True,
        traveler=False,
        battery_priority=0.5,
        performance_priority=0.9,
        camera_priority=0.85,
        storage_priority=0.85,
        price_sensitivity=0.5,
        upgrade_frequency="yearly",
        owned_products=(),
        wishlist=("sa-laptop-loq-15", "sa-phone-galaxy-s25-ultra"),
        favorite_categories=("laptop", "phone"),
        accessories_owned=(),
        description="Needs strong GPU for editing plus solid camera phone.",
    ),
    _profile(
        profile_id="profile-apple-fan",
        display_name="Apple Fan",
        persona="apple_fan",
        budget=80000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Shopee",),
        favorite_brands=("Apple",),
        disliked_brands=("Samsung", "Google", "Acer"),
        preferred_screen_sizes=("13", "6.3"),
        preferred_colors=("midnight", "titanium", "white"),
        gaming=False,
        office_work=True,
        student=False,
        creator=True,
        traveler=True,
        battery_priority=0.85,
        performance_priority=0.7,
        camera_priority=0.8,
        storage_priority=0.55,
        price_sensitivity=0.25,
        upgrade_frequency="yearly",
        owned_products=("sa-earbuds-airpods-pro-2",),
        wishlist=(IPHONE_DEMO_PRODUCT_ID, "sa-laptop-macbook-air-m3"),
        favorite_categories=("phone", "laptop", "earbuds"),
        accessories_owned=("sa-earbuds-airpods-pro-2",),
        description="Stays in Apple ecosystem; brand affinity outweighs absolute price.",
    ),
    _profile(
        profile_id="profile-android-fan",
        display_name="Android Fan",
        persona="android_fan",
        budget=65000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Lazada", "Shopee"),
        favorite_brands=("Samsung", "Google", "ASUS"),
        disliked_brands=("Apple",),
        preferred_screen_sizes=("6.7", "6.8"),
        preferred_colors=("black", "gray"),
        gaming=True,
        office_work=True,
        student=False,
        creator=False,
        traveler=False,
        battery_priority=0.7,
        performance_priority=0.75,
        camera_priority=0.8,
        storage_priority=0.75,
        price_sensitivity=0.55,
        upgrade_frequency="yearly",
        owned_products=(),
        wishlist=("sa-phone-galaxy-s25-ultra", "sa-phone-pixel-9"),
        favorite_categories=("phone", "laptop"),
        accessories_owned=(),
        description="Prefers Android flexibility and S Pen / Pixel camera options.",
    ),
    _profile(
        profile_id="profile-minimalist-buyer",
        display_name="Minimalist Buyer",
        persona="minimalist_buyer",
        budget=45000.0,
        currency="PHP",
        country="PH",
        preferred_marketplaces=("Shopee",),
        favorite_brands=("Google", "Apple"),
        disliked_brands=(),
        preferred_screen_sizes=("6.1", "13"),
        preferred_colors=("white", "silver"),
        gaming=False,
        office_work=True,
        student=False,
        creator=False,
        traveler=True,
        battery_priority=0.8,
        performance_priority=0.5,
        camera_priority=0.55,
        storage_priority=0.4,
        price_sensitivity=0.7,
        upgrade_frequency="rare",
        owned_products=(),
        wishlist=("sa-phone-pixel-9", "sa-laptop-macbook-air-m3"),
        favorite_categories=("phone", "laptop"),
        accessories_owned=(),
        description="Buys less often; values simplicity, battery, and clean software.",
    ),
)


def list_demo_profiles() -> list[CustomerProfile]:
    return list(DEMO_PROFILES)


def get_demo_profile(profile_id: str) -> CustomerProfile | None:
    cleaned = profile_id.strip()
    for profile in DEMO_PROFILES:
        if profile.profile_id == cleaned:
            return profile
    return None


def default_profile() -> CustomerProfile:
    profile = get_demo_profile(DEFAULT_PROFILE_ID)
    assert profile is not None
    return profile


def catalog_product_map() -> dict[str, dict[str, Any]]:
    return {str(item["product_id"]): dict(item) for item in get_catalog()}
